version: '3'

services:
  web:
    build: .
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8001:8000
    volumes:
      - media_file:/app/media
      - static_file:/app/static
    environment:
      - TZ=Asia/Tashkent

  postgres:
    image: postgres:latest
    container_name: "postgres_l"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "../app_data:/var/lib/postgresql/data"
    ports:
      - "5434:5432"
    command: postgres -c max_connections=1500

volumes:
  media_file:
  static_file:
