version: '3'

services:
  web:
    build: .
    command: gunicorn root.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - media_file:/app/media
      - static_file:/app/static
    environment:
      - TZ=Asia/Tashkent

  postgres:
    image: postgres:latest
    container_name: "postgres"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "../app_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    command: postgres -c max_connections=1500

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - media_file:/app/media
      - static_file:/app/static
    depends_on:
      - web
    environment:
      - TZ=Asia/Tashkent

volumes:
  media_file:
  static_file: