services:

    postgres:
        image: postgres:latest
        container_name: "postgres_l"
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - TZ=Asia/Tashkent
        volumes:
            - "../app_data:/var/lib/postgresql/data"
        ports:
            - "5432:5432"
        command: postgres -c max_connections=1500

    django:
        container_name: django_l
        build:
            context: ./config
        command: python manage.py runserver 0.0.0.0:8000

        volumes: &shared_volumes
            - ./config:/usr/src/app
        ports:
            - 8001:8000
        env_file:
            - .env
        depends_on:
            - postgres
